spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3306/cardsapi
    username: root
    password: "!panagiota04"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: embedded
      continue-on-error: true
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql
