INSERT INTO cards (name,description,color,user_id)
VALUES
        ('p1', 'new card after flyway ', '#abc123',1),
        ('p2', 'new card after flyway ', '#abc123',2),
        ('p3', 'new card after flyway ', '#abc123',1),
        ('p4', 'new card after flyway ', '#abc123',4),
        ('p5', 'new card after flyway ', '#abc123',1),
        ('p6', 'new card after flyway ', '#abc123',1),
        ('p7', 'new card after flyway ', '#abc123',2),
        ('p8', 'new card after flyway ', '#abc123',2),
        ('p9', 'new card after flyway ', '#abc123',4),
        ('p10', 'new card after flyway ', '#abc123',3),
        ('p11', 'new card after flyway ', '#abc123',3),
        ('p12', 'new card after flyway ', '#abc123',4),
        ('p13', 'new card after flyway ', '#abc123',2),
        ('p14', 'new card after flyway ', '#abc123',2),
        ('p15', 'new card after flyway ', '#abc123',3),
        ('p16', 'new card after flyway ', '#abc123',1),
        ('p17', 'new card after flyway ', '#abc123',1),
        ('p18', 'new card after flyway ', '#abc123',4),
        ('p19', 'new card after flyway ', '#abc123',3),
        ('p20', 'new card after flyway ', '#abc123',2),
        ('p21', 'new card after flyway ', '#abc123',1),
        ('p22', 'new card after flyway ', '#abc123',3);
